### ISSUE TITLE
compatibility with spring-boot-starter-data-rest

### ISSUE THREAD

**Issue by qwazer** [Microsoft/spring-data-documentdb#21]
is it possible to use spring-data-documentdb
 with  spring-boot-starter-data-rest?

When I add spring-boot-starter-data-rest to classpath I get

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.rest.core.mapping.RepositoryResourceMappings]: Factory method 'resourceMappings' threw exception; nested exception is java.lang.IllegalArgumentException: PersistentEntity must not be null!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 99 common frames omitted
Caused by: java.lang.IllegalArgumentException: PersistentEntity must not be null!
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.data.rest.core.mapping.RepositoryAwareResourceMetadata.<init>(RepositoryAwareResourceMetadata.java:52)
	at org.springframework.data.rest.core.mapping.RepositoryResourceMappings.populateCache(RepositoryResourceMappings.java:90)
	at org.springframework.data.rest.core.mapping.RepositoryResourceMappings.<init>(RepositoryResourceMappings.java:76)
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration.resourceMappings(RepositoryRestMvcConfiguration.java:619)
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$a7067e45.CGLIB$resourceMappings$53(<generated>)
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$a7067e45$$FastClassBySpringCGLIB$$c23b2549.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$a7067e45.resourceMappings(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 100 common frames omitted

**Comment by yungez** [comment]
@qwazer  Hi, could you pls help to share your pom configuration to help reproduce the issue? the error is from build or run phase? if run phase, could you pls share little bit of your scenario? thanks.

**Comment by qwazer** [comment]
@yungez Yes.
Take a look:
https://github.com/qwazer/spring-data-documentdb/commit/cbf33d684e84d4cb2f24fde57587f3bb5a69eb39

**Comment by yungez** [comment]
#24

**Comment by qwazer** [comment]
Thanks. We will check

**Comment by yungez** [comment]
spring-data-documentdb 0.1.3 released to maven repo. close the issue. pls submit new issue if any furthur question. thanks.
